#!/bin/sh

# run prettier on staged files
# JFYI @Martin this was disabled to avoid conflicting code styles to be applied to changed files and thus make it harder to merge upstream changes
# npx lint-staged

# typecheck
make lint
